version: '3'

services:
    db:
        image: jstagg/repo:dradis-back
        container_name: dradis-back
        ports:
            - "6379:6379"
    web:
        image: jstagg/repo:dradis-front
        container_name: dradis-front
        ports:
            - "8888:8888"
        depends_on: 
            - db
        restart: always
