version: '3'

services:
    db:
        image: dradis-back:latest
        container_name: dradis-back
        ports:
            - "6379:6379"
    web:
        image: dradis-front:latest
        container_name: dradis-front
        ports:
            - "8888:8888"
        depends_on: 
            - db
        restart: always
